adding new feature isReviewed
davidsaulrodriguez/shop-portal pull request #55
Opened 2021-04-10 22:54 UTC by lucpizz

## Proposed changes

This feature allows users/customers to add a review of the product after they purchase it.

## PR Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/davidsaulrodriguez/shop-portal/blob/master/CONTRIBUTING.md) doc
- [x] I have read the [BRANCHING MODEL](https://github.com/davidsaulrodriguez/shop-portal/blob/master/BRANCHINGMODEL.md) doc
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## PR Type

What types of changes does your code introduce to **Shop Portal**?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code Style Update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Other (Please describe):

## Current behavior

Issue Number: #54 

## New behavior

Fixes #54 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Further comments

N/A

2021-04-11 17:52 UTC, davidsaulrodriguez requested changes
A bug was introduced. Please review the comment I dropped on the line of code that introduces this bug.

2021-04-11 17:52 UTC, davidsaulrodriguez commented on controllers/isReviewedController.js
> +    db.find(req.query)
**this is pretty a serious bug**

```javascript
db.find(req.query) // Not Compliant
```

User provided data such as URL parameters, POST body-content should always be considered untrusted and tainted. Applications performing NoSQL operations based on tainted data could be exploited in a way similar to SQL Injection, where an attacker could inject NoSQL objects to access sensitive information or compromise data integrity.

To fix this and have a _compliant solution_ the data should be sanitized like so:

**example**

```javascript
function (req, res) {
  let query = { user: req.query.user.toString(), city: req.query.city.toString() };

  db.collection("users")
    .find(query) // Compliant
    .toArray((err, docs) => { });
}
```

2021-04-11 18:03 UTC, lucpizz commented on controllers/isReviewedController.js
> +    db.find(req.query)
I added a fix by setting the query to a "toString()" method.

`findAll: function (req, res) {
    db.find(req.query.toString())`

2021-04-14 15:40 UTC, lucpizz commented on controllers/isReviewedController.js
> +    db.find(req.query)
implemented a fix 

  create: function (req, res) {
    let reviewData = new db({
      name: req.body.name,
      imageUrl: req.body.imageUrl,
      imageKey: req.body.imageKey,
      description: req.body.description,
      totalStars: req.body.totalStars,
      reviewBody: req.body.reviewBody,
      isActive: req.body.isActive,
      isReviewable: req.body.isReviewable,
      created: req.body.created,
      updated: req.body.updated,
    });

    db.create(reviewData)
      .then((dbModel) => res.json(dbModel))
      .catch((err) => res.status(422).json(err));
  },

2021-04-14 15:41 UTC, lucpizz reviewed
reviewed the files

2021-04-15 00:13 UTC, davidsaulrodriguez approved these changes
Let's start getting this thing merged!

2021-04-15 00:36 UTC, Delph-Sunny approved these changes
Ok

2021-04-15 01:06 UTC, merged